server:
   port: 8001
spring:
   application:
      name: cloud-payment-service
   datasource:
      name: test
      url: jdbc:mysql://192.168.0.200:3306/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 117805
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
   mvc:
      static-path-pattern: /**
   devtools:
      restart:
         enable: true
         additional-paths: src/main/java
eureka:
   client:
      #表示是否将自己注册进EurekaServer,默认为true
      register-with-eureka: true
       #是否从EurekaServer抓取自己的注册信息，默认为true，集群必须设置为true才能配合ribbon使用负载均衡
      fetchRegistry: true
      service-url:
         #defaultZone: http://localhost:7001/eureka 单机版
         defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka/ #集群版
   instance: 
      instance-id: payment8001
      prefer-ip-address: true  #访问路径可以显示ip地址。
      
mybatis:
   mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      lazy-loading-enabled: true
      aggressive-lazy-loading: false #false 为按需加载